### ISSUE TITLE
Ability to Extend Window Size and adding NamePaths such as BuildName, CreateName, ModifName

### ISSUE THREAD

**Issue by firebreath1001** [mortany/OGF-tool#1]
I've just started using your amazing tool and would like to suggest if it would be possible to increase the **window length** of the application as it might be more user-friendly for path lengths that go beyond the length of the text-box as in the image given below:

![image](https://user-images.githubusercontent.com/31083898/150025744-6ad9d222-32d6-40f2-95f7-565103b7c61e.png)

Also, on a side note, if it would be possible to add text fields for **BuildName**, **CreateName**, **ModifName** like in the old _ogf-data-changer_, it would be awesome. 
![image](https://user-images.githubusercontent.com/31083898/150026163-6535e485-a5d2-4963-80ec-362961409d6d.png)

I really enjoy the modern look and feel of the tool overall. Thank you ^^

**Comment by mortany** [comment]
1) Its possible, but we can't allow user to change window borders, because all textboxes dynamically created.
2) Why? This is some useless information in ogf.

**Comment by firebreath1001** [comment]
Oh I understand, no problem then, I'll close the issue. Thank you though.

**Comment by mortany** [comment]
@firebreath1001 if u really want change BuildName, CreateName, ModifName i can add editboxes for it, because this infrormation parsed but not used right now. P.S. game engine dont parse this info too

**Comment by mortany** [comment]
About UI... I am open for any UI style suggestion, beacuse am noob in ui design)

**Comment by firebreath1001** [comment]
Ooh that'll be cool, well its sort of like adding credits to the model I guess, but if it takes too much window space its alright

**Comment by firebreath1001** [comment]
Sure! This UI is miles better than the ogf-data-changer :D

my bad, I accidentally closed the issue 
![dead-inside](https://user-images.githubusercontent.com/31083898/150090116-4b7ad5bd-1662-4b78-a119-888daad42703.png)

**Comment by Blackgrowl** [comment]
> 2. Why? This is some useless information in ogf.

I can only give the argument that it's for "privacy" reasons, some people have their PC named as their real name or so and they prefer to not be shown over the internet or over game files.

**Comment by mortany** [comment]
> I can only give the argument that it's for "privacy" reasons

kk, its good reason
