### ISSUE TITLE
Ability to change "Skeleton" data, including Userdata, Motion Reference, LOD Path...

### ISSUE THREAD

**Issue by Blackgrowl** [mortany/OGF-tool#2]
I remember in AXRToolset's "OGF Viewer", I was able to change a bunch of stuff that another OGF Editor was not able to.
Namely, Skeleton Userdata, Skeleton motion_refs1 and Skeleton motion_refs2 ("Skeleton Bones" too, but I think that was just for view)

To be more specific about the "Skeleton Userdata", this is an example:
#include "models\capture\stalker_nebo_1.ltx"

With that in mind, would it be possible to add mentioned features? Or at the very least, "Skeleton Userdata" since that one is very useful.

**Comment by mortany** [comment]
Skeleton motion_refs1 and Skeleton motion_refs2  == motion refs window.
Skeleton Userdata  == custom userdata window,
